{"timestamp":1730139950770,"message":"Failed to start API","log.level":"ERROR","logger.name":"processes.api","thread.id":140218547846016,"thread.name":"MainThread","process.id":2325,"process.name":"MainProcess","file.name":"/home/runner/work/drb-etl-pipeline/drb-etl-pipeline/processes/api.py","line.number":27,"entity.type":"SERVICE","error.class":"builtins:Exception","error.message":"Connection error"}
