ERROR    api.blueprints.drbCollection:drbCollection.py:290 Unable to get collection with id d902fd44-7cbe-4401-b50c-5b1bda8b1059
Traceback (most recent call last):
  File "/home/runner/work/drb-etl-pipeline/drb-etl-pipeline/api/blueprints/drbCollection.py", line 277, in get_collection
    collection = db_client.fetchSingleCollection(uuid)
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/unittest/mock.py", line 1092, in __call__
    return self._mock_call(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/unittest/mock.py", line 1096, in _mock_call
    return self._execute_mock_call(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/unittest/mock.py", line 1151, in _execute_mock_call
    raise effect
Exception: Database error