{"timestamp":1729885171924,"message":"Unable to get collections","log.level":"ERROR","logger.name":"api.blueprints.drbCollection","thread.id":139914717178752,"thread.name":"MainThread","process.id":2348,"process.name":"MainProcess","file.name":"/home/runner/work/drb-etl-pipeline/drb-etl-pipeline/api/blueprints/drbCollection.py","line.number":404,"entity.type":"SERVICE","error.class":"builtins:Exception","error.message":"Database error"}
